-- AlterTable
ALTER TABLE `availabilityrule` ADD COLUMN `currency` VARCHAR(191) NOT NULL DEFAULT 'INR',
    ADD COLUMN `isFree` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `price` INTEGER NOT NULL DEFAULT 0;

-- AlterTable
ALTER TABLE `slot` ADD COLUMN `currency` VARCHAR(191) NOT NULL DEFAULT 'INR',
    ADD COLUMN `isFree` BOOLEAN NOT NULL DEFAULT true,
    ADD COLUMN `price` INTEGER NOT NULL DEFAULT 0;
